main/urls.py
from django.urls import path,include
from . import views
from .models import NonficViewSet,TodoListViewSet
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'users', NonficViewSet)
router.register(r'Todolist',TodoListViewSet)
app_name ="main"
urlpatterns = [

#==================== Django REST Framework =========================
     path('route/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
#=========================================================================
    path('', views.index ),
    path("home/",views.home, name="home"),
    path("login/", views.auth_login, name="auth_login"),
    path("signUp/", views.auth_signup, name="auth_signUp"),
    path("signUp/verification/<str:PostUsername>/<str:PostPassword>/", views.auth_verification, name="auth_verification"),
    path("signUp/verification/success", views.auth_success_verify, name="success_verify"),
# ======================== Site Pages ====================
    path('homeSite/<int:id>/', views.site_home, name="site_home"),

# ====================== Admin Pages ============================
   path('homeSite/admin/<int:id>/', views.admin_page, name="admin_page"),


#======================== Roles =================================
   path('homeSite/admin/<int:id>/roles/', views.role_page, name="role_page"),

    path('homeSite/admin/<int:id>/roles/add', views.role_page_ADD, name="role_page_ADD"),
     path('homeSite/admin/<int:id>/<str:user>/roles/edit', views.role_page_EDIT, name="role_page_EDIT"),

# ======================= User Pages =====================
# ======================== Books ============================
# ======================= Nonfiction =========================
    path('home/books/<int:id>', views.user_books, name="user_books"),
    path("home/books/<int:id>/nonfiction",views.nonfic_books, name='nonfic_books' ),
       path("home/books/<int:id>/nonfiction/ADD", views.nonfic_books_ADD, name="nonfic_books_ADD"),
    path("home/books/<int:id>/nonfiction/GET", views.nonfic_books_GET, name="nonfic_books_GET"),
       path("home/books/<int:id>/nonfiction/DELETE", views.nonfic_books_DELETE, name="nonfic_books_DELETE"),
        path("home/books/<int:id>/nonfiction/EDIT", views.nonfic_books_EDIT, name="nonfic_books_EDIT"),
# ======================= Fiction ======================================
path("home/books/<int:id>/fiction", views.fiction_books, name="fiction_books"), 
 
# ======================== Art ===============================
    path('home/art/<int:id>', views.user_art, name="user_art"),
# ========================= Todo ===============================
   path("home/todo/<int:id>", views.user_todo, name="user_todo"),
   path("home/todo/<int:id>/GET", views.user_todo_GET, name="user_todo_GET"),
   path("home/todo/<int:id>/ADD", views.user_todo_ADD, name="user_todo_ADD"),
 path("home/todo/<int:id>/EDIT", views.user_todo_EDIT, name="user_todo_EDIT"),
  path("home/todo/<int:id>/DELETE", views.user_todo_DELETE, name="user_todo_DELETE"),

]

website_proj7_08_2023_bookFullpledge/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
     path("",include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from rest_framework import serializers,viewsets
# Create your models here.
from website_proj7_08_2023_bookFullpledge import settings

# Create your models here.


  


class UserSite(models.Model):
    id = models.AutoField(primary_key=True)
    username=models.CharField(max_length=
                              250, unique=True)
    email = models.CharField(max_length=128)
    password = models.CharField(max_length=1024)
    def save(self, *args, **kwargs):
        self.password = make_password(self.password)
        super(UserSite, self).save(*args, **kwargs)
    def __str__(self):
        return self.username
class Role(models.Model):
     user_ref = models.ForeignKey(UserSite, on_delete=models.CASCADE)
     user_role = models.BooleanField(default=False)
     admin_role = models.BooleanField(default=False)
     def __str__(self):
        return self.user_ref.email


class NonFictionBook(models.Model):
    id = models.AutoField(primary_key=True)
    user_ref = models.ForeignKey(UserSite, on_delete=models.CASCADE)
    author = models.CharField(max_length=250)
    current_page =models.IntegerField(blank=True, null=True)
    last_page= models.IntegerField(blank=True, null=True)
    bookImage = models.FileField(upload_to="uploads/book-img/", null=True, blank=True)
    bookFile = models.FileField(upload_to="uploads/book-file/", null=True, blank=True)
    book_name = models.CharField(max_length=250)
    date_modified = models.DateField(auto_now=True, null=True,blank=True)


class BookUpdate(models.Model):
     id = models.AutoField(primary_key=True)
     user = models.CharField(max_length=250, null=True)
     book_title = models.CharField(max_length=250, null=True)
     actions = models.CharField(max_length=250 , null=True)
     date_action_created = models.DateField(auto_now_add=True , null=True)


class TodoUpdate(models.Model):
     id = models.AutoField(primary_key=True)
     user = models.CharField(max_length=250)
     description = models.CharField(max_length=250)
     actions = models.CharField(max_length=250)
     date_action_created = models.DateField(auto_now_add=True)

class NonficSerializer(serializers.HyperlinkedModelSerializer):
        """
        bookFile_url = serializers.SerializerMethodField()
        bookImage_url = serializers.SerializerMethodField()
        def get_bookFile_url(self, obj):
            request = self.context.get('request')
            if obj.bookFile:
                absolute_url = obj.bookFile.url
                base_url = request.build_absolute_uri('/')
                relative_url = absolute_url.replace(base_url, '', 1)
                return relative_url
            return None
        def get_bookImage_url(self, obj):
            request = self.context.get('request')
            if obj.bookImage:
                absolute_url = obj.bookImage.url
                base_url = request.build_absolute_uri('/')
                relative_url = absolute_url.replace(base_url, '', 1)
                return relative_url
            return None  
        """
        class Meta:
            model = NonFictionBook
            fields = ('id','author', 'bookImage', "bookFile",'book_name',"last_page","current_page","date_modified")
            #fields = ('id','author', 'bookImage_url', "bookFile_url",'book_name')
  
   
class NonficViewSet(viewsets.ModelViewSet):
    queryset = NonFictionBook.objects.all()
    serializer_class = NonficSerializer


class TodoList(models.Model):
     id = models.AutoField(primary_key=True)
     user_ref = models.ForeignKey(UserSite, on_delete=models.CASCADE)
     task_description = models.CharField(max_length=250)
     completed = models.BooleanField(default=False)
     due_date = models.DateField()
     

class TodoListSerializer(serializers.HyperlinkedModelSerializer):
     class Meta:
          model = TodoList
          fields = ('id','task_description','completed', 'due_date')

class TodoListViewSet(viewsets.ModelViewSet):
     queryset = TodoList.objects.all()
     serializer_class = TodoListSerializer


class SiteVisited(models.Model):
     id = models.AutoField(primary_key=True)
     date_visited = models.DateField(auto_created=True)
     number_visitor = models.IntegerField()

main/views.py
from django.shortcuts import render,redirect
import json
from django.http import JsonResponse
from django.core.signing import Signer, BadSignature
import math
from website_proj7_08_2023_bookFullpledge import settings
from django.contrib.auth.hashers import make_password, check_password
from .models import UserSite, NonFictionBook, NonficViewSet, NonficSerializer, TodoList, TodoListSerializer, Role, BookUpdate, TodoUpdate, SiteVisited
import plotly.express as px
import pandas as pd
def index(request):
    context = {}
    return render(request, 'main/index.html', context)

def home(request):
    context ={}
    return render(request, 'main/home.html', context)

def auth_login(request):
    if request.method == "POST":
        json_data = json.loads(request.body)
        
        try:
            u = UserSite.objects.get(username =json_data['username'])
            security_pass = check_password(json_data['password'],u.password)       
            if(not security_pass):
                return JsonResponse({'msg':"Server err"}, status = 500)
            else:
                
                context ={
                    "id":u.id
                }
                return JsonResponse({"id":context}, status = 200)
        except:
            pass
    context = {}
    return render(request, 'main/login.html', context)

def auth_signup(request):
    if request.method == "POST":

        json_data = json.loads(request.body)
        if(json_data['username'] and json_data['password']):
            try:
                u  = UserSite.objects.filter(username =json_data['username'])
                if(u):
                    return JsonResponse({"msg":"The username has been used"},status=500)
            except:
                pass
            signer = Signer()
            username_sh = signer.sign(json_data['username'])
            password_sh = signer.sign(json_data['password'])
            context ={
                "username_sh":username_sh,
                "password_sh":password_sh,
            }  
            return JsonResponse({"data":context})
    context = {}
    return render(request, 'main/signup.html', context)

def auth_verification(request, PostPassword, PostUsername):
    if request.method =="POST":
        json_data = json.loads(request.body)
       
        signer = Signer()
        username = signer.unsign(json_data["username"])
        password = signer.unsign(json_data["password"])
     
        u = UserSite()
        lastID = UserSite.objects.values('id').last()
        u.id = lastID['id'] +1
        u.username = username
        u.password =password
        u.email = json_data['email']
        u.save() 
        return JsonResponse({"msg":"Data has been successfuly sent"})    
    context = {
        "PostPassword": PostPassword,
        "PostUsername":PostUsername,
    }
    return render(request, 'main/verification-site/verification.html', context)

def auth_success_verify(request):
    context = {}
    return render(request, "main/verification-site/verify-success.html", context)

# ========================== SITE PAGES ==================

def site_home(request, id):
    u = UserSite.objects.get(id=id)
    r = Role.objects.get(user_ref = u)
    if(r.admin_role):
        url=f"/homeSite/admin/{id}/"
        return redirect(url)
        """
         context = {
                  "id": u.id
         }
         return render(request, "main/site/admin/admin-home-page.html", context)
        """
    elif(r.user_role):
         context = { 
             "username":u.username,
             "id": u.id
         }
         return render(request, "main/site/user/user-home-page.html", context)
    else:
        url="/signUp/verification/success"
        return redirect(url)

#============================= ADMIN PAGE ==========================
def admin_page(request, id ):
    b = BookUpdate.objects.all().order_by("date_action_created")
    t = TodoUpdate.objects.all().order_by("date_action_created")
    user_count = UserSite.objects.all().count()
    visitors = SiteVisited.objects.all().order_by("date_visited")
   
    data = {
        'date_visited': [visitor.date_visited for visitor in visitors],
        'number_visitor': [visitor.number_visitor for visitor in visitors],
    }
    df = pd.DataFrame(data)
    #fig = px.bar(df, x=visitors.date_visited, y= visitors.number_visitor)
    fig = px.bar(df, x='date_visited', y='number_visitor', title='Bar Chart of Visitors')     
    chart_html = fig.to_html(full_html=False)
    context = {
            "id": id,
            "BookUpdate_Collection": b,
            "TodoList_Collection":t,
            "user_count":user_count,
            "chart_html":chart_html, 
    }
    return render(request, "main/site/admin/admin-home-page.html", context)

# ========================= ROLES =========================
def role_page(request, id):
    u_username = UserSite.objects.get(id=id)
    r_users = Role.objects.filter(user_role = True).order_by("user_ref__username")
    r_admin = Role.objects.filter(admin_role = True).order_by("user_ref__username")

    context = {
        "id":id,
         "username":u_username,
         "user_roles": r_users,
         "admin_roles": r_admin,
         
    }  
    return render(request,"main/site/admin/roles/home-roles.html", context)

def role_page_ADD(request, id):
    u = UserSite.objects.all().order_by("username")

    if request.method == "POST":
        json_data = json.loads(request.body)
        u_ref = UserSite.objects.get(username = json_data['username'])
        r = Role.objects.get(user_ref = u_ref)
        r.user_role = json_data['role_user']
        r.admin_role = json_data["role_admin"]
        r.save()
        return JsonResponse({"msg":"Data has been successfuly sent"})   
      


       
    context ={
        "id":id,
        "users_choose":u,
        

    }
    return render(request, "main/site/admin/roles/add-roles.html", context )

def role_page_EDIT(request,id,user):
    u = UserSite.objects.get(id=id)
    r = Role.objects.get(user_ref =u)
    redirect_ID = UserSite.objects.get(username = user)
    context = {
        "id":id,
        "user":u,
        "roles":r,
        "redirect_ID":redirect_ID,

    }
    if (request.method =="POST"):
        json_data = json.loads(request.body)
        print(json_data)
        user = UserSite.objects.get(username = json_data['username'])
        role = Role.objects.get(user_ref = user)
        role.user_role = json_data['role_user']
        role.admin_role = json_data['role_admin']
        role.save()
        return JsonResponse({"msg":"Data has been successfuly sent"})   
        #print("this is for post edit")
        
    return render(request,"main/site/admin/roles/edit-roles.html", context)
# =============================== USER PAGES =======================
#========================== BOOKS ================================
def user_books(request,id):
    
    u = UserSite.objects.get(id=id)

    context = {
         "username":u.username,
         "id": u.id
    }
    return render(request, "main/site/user/books/book-choice.html", context)

# ======================= NONFICTION  ==========================================
def nonfic_books_ADD(request,id):
    if request.method =="POST":
        u = UserSite.objects.get(id=id)
       
      
        n = NonFictionBook()
        LastID = NonFictionBook.objects.values("id").last()
        n.id = LastID['id'] + 1
        n.user_ref = u
        n.bookImage = request.FILES.get("inp_file_image")
        n.bookFile = request.FILES.get("inp_file_book")
        n.author = request.POST.get("inp_file_author")
        n.book_name = request.POST.get("inp_file_BookName")
        n.save()
        n =  NonFictionBook.objects.get(id = LastID['id'] + 1 )
        updates = BookUpdate()
        updatesLastID = BookUpdate.objects.values("id").last()
        updates.id = updatesLastID['id'] + 1
        updates.user = n.user_ref.username
        updates.book_title = n.book_name
        updates.actions = "Added"
        updates.save()
    
    return JsonResponse({"msg":"operation complete"},status=200)
def nonfic_books_EDIT(request,id):
    if(request.method  == "GET"):
     
        n = NonFictionBook.objects.get(id=id)
        serializer =  NonficSerializer(n)
        return JsonResponse({"data":(serializer.data)},status=200, content_type="application/json")
    elif(request.method =="POST"):

        n = NonFictionBook.objects.get(id=id)
        updates = BookUpdate()
        updatesLastID = BookUpdate.objects.values("id").last()
        updates.id = updatesLastID['id'] + 1
        updates.user = n.user_ref.username
        updates.book_title = n.book_name
        updates.actions = "Edited"
        updates.save()
        book_image = request.FILES.get('inp_file_image') or None
        book_file = request.FILES.get("inp_file_BookName") or None
        n.author = request.POST.get("inp_file_author")
        n.book_name = request.POST.get("inp_file_BookName")
        if(book_image != None):
            n.bookImage = book_image
        if(book_file != None):
            n.bookFile = book_file
        n.save()
        # if(request.FILES('get')):
        #     print("have file")

        return JsonResponse({"msg": "has been accomplish"}, status =200 )
   

def nonfic_books_GET(request,id):
    u = UserSite.objects.get(id =id)
    if request.method == "GET":
        nonfic_collection = NonFictionBook.objects.filter(user_ref = u.id).order_by("book_name")
        serializer = NonficSerializer(nonfic_collection, many=True)
        return JsonResponse({"data":(serializer.data)},status=200, content_type="application/json")
    
def nonfic_books_DELETE(request,id):
    if request.method =="POST":
        json_data = json.loads(request.body)
       
        n = NonFictionBook.objects.get(id = json_data['id'])
        updates = BookUpdate()
        updatesLastID = BookUpdate.objects.values("id").last()
        updates.id = updatesLastID['id'] + 1

main/templates/main/site/user/user-home-page.html
{% extends '../../site/base.html' %}

<head>
  {% block title %}
  <title>Home Page</title>
  {% endblock title%} {% block styles %}

  <style>
    .inherit-width {
      width: 100%;
    }
  </style>

  {% endblock styles %}
</head>
{% load static %}
<body>
  {% block content %}
  <div class="hero is-fullheight">
    <div class="hero-body">
      <div class="inherit-width">
        <div class="columns is-vcentered is-variable is-8-desktop">
          <div class="column">
            <img src="{% static 'main/homepage/user/apple2.jpg' %}" />
          </div>
          <div class="column section-bkg-menuANDcontent">
            <h1 class="style-header-content has-text-centered">Books</h1>
            <p class="style-subheader-content">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam
              dolore suscipit exercitationem rerum delectus ex, dolorum nam
              assumenda illo aspernatur fugiat dolor! Ipsam illo nisi voluptate
              ad modi sed molestias, quia maiores, esse quaerat autem accusamus
              inventore distinctio commodi fugit architecto. Asperiores dolor,
              sapiente debitis aut vel autem ex aliquam alias ad id, nisi unde
              consectetur neque, quas voluptatum beatae nostrum aliquid soluta
              magnam impedit officiis quis odio. Quasi totam quis quo blanditiis
              quia ea nihil, ex nisi. Sequi dolorum, consequuntur minima sed
              illum, eius, quod corrupti excepturi dolorem similique eligendi
              nam voluptate. Possimus, distinctio porro error a eaque in?
            </p>
            <div class="has-text-centered">
              <a
                href="{% url 'main:user_books' id=id %}"
                class="button style-btn-content"
              >
                View Books
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="hero is-fullheight">
    <div class="hero-body">
      <div class="inherit-width">
        <div class="columns is-vcentered is-variable is-8-desktop">
          <div class="column section-bkg-menuANDcontent">
            <h1 class="style-header-content has-text-centered">Art</h1>
            <p class="style-subheader-content">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam
              dolore suscipit exercitationem rerum delectus ex, dolorum nam
              assumenda illo aspernatur fugiat dolor! Ipsam illo nisi voluptate
              ad modi sed molestias, quia maiores, esse quaerat autem accusamus
              inventore distinctio commodi fugit architecto. Asperiores dolor,
              sapiente debitis aut vel autem ex aliquam alias ad id, nisi unde
              consectetur neque, quas voluptatum beatae nostrum aliquid soluta
              magnam impedit officiis quis odio. Quasi totam quis quo blanditiis
              quia ea nihil, ex nisi. Sequi dolorum, consequuntur minima sed
              illum, eius, quod corrupti excepturi dolorem similique eligendi
              nam voluptate. Possimus, distinctio porro error a eaque in?
            </p>
            <div class="has-text-centered">
              <a
                href="{% url 'main:user_art' id=id %}"
                class="button style-btn-content"
              >
                View Art
              </a>
            </div>
          </div>
          <div class="column">
            <img src="{% static 'main/homepage/user/apple2.jpg' %}" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="hero is-fullheight">
    <div class="hero-body">
      <div class="inherit-width">
        <div class="columns is-vcentered is-variable is-8-desktop">
          <div class="column">
            <img src="{% static 'main/homepage/user/apple2.jpg' %}" />
          </div>
          <div class="column section-bkg-menuANDcontent">
            <h1 class="style-header-content has-text-centered">Todo List</h1>
            <p class="style-subheader-content">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam
              dolore suscipit exercitationem rerum delectus ex, dolorum nam
              assumenda illo aspernatur fugiat dolor! Ipsam illo nisi voluptate
              ad modi sed molestias, quia maiores, esse quaerat autem accusamus
              inventore distinctio commodi fugit architecto. Asperiores dolor,
              sapiente debitis aut vel autem ex aliquam alias ad id, nisi unde
              consectetur neque, quas voluptatum beatae nostrum aliquid soluta
              magnam impedit officiis quis odio. Quasi totam quis quo blanditiis
              quia ea nihil, ex nisi. Sequi dolorum, consequuntur minima sed
              illum, eius, quod corrupti excepturi dolorem similique eligendi
              nam voluptate. Possimus, distinctio porro error a eaque in?
            </p>
            <div class="has-text-centered">
              <a
                href="{% url 'main:user_todo' id=id %}"
                class="button style-btn-content"
              >
                Create Todo List
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content%}
</body>